post:
  content:
    application/json:
      schema:
        type: object
        properties:
          configDefaultId:
            type: integer
          optionalList:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                brandId:
                  type: integer
                isDeleted:
                  type: boolean
                attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      value:
                        type: integer
