get:
  200:
    content:
      application/json:
        schema:
          allOf:
            - $ref: Success.yml
            - type: object
              properties:
                result:
                  type: object
                  properties:
                    configDefaultId:
                      type: integer
                    optionalList:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          brandId:
                            type: integer
                          attributes:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                value:
                                  type: integer
  400:
    $ref: ClientErrors.yml#/BadRequest
  500:
    $ref: ServerErrors.yml#/InternalServer

post:
  200:
    content:
      application/json:
        schema:
          $ref: Success.yml
  400:
    $ref: ClientErrors.yml#/BadRequest
  500:
    $ref: ServerErrors.yml#/InternalServer
