get:
  200:
    content:
      application/json:
        schema:
          allOf:
            - $ref: Success.yml
            - type: object
              properties:
                result:
                  type: object
                  properties:
                    attributeSetName:
                      type: string
                    brandName:
                      type: string
                    attribute1Name:
                      type: string
                    attribute1Value:
                      type: string
                    attribute2Name:
                      type: string
                    attribute2Value:
                      type: string
                    attribute3Name:
                      type: string
                    attribute3Value:
                      type: string
                    attribute4Name:
                      type: string
                    attribute4Value:
                      type: string
                    attribute5Name:
                      type: string
                    attribute5Value:
                      type: string
                    isDefault:
                      type: boolean
  400:
    $ref: ClientErrors.yml#/BadRequest
  500:
    $ref: ServerErrors.yml#/InternalServer
