lang: nodejs

before_install:
  - npm install redoc-cli
  - export PATH=$(npm bin):$PATH

script:
  - redoc-cli bundle -o build/index.html openapi.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master
