openapi: 3.0.0
info:
  title: Catalog
  description: Product management system
  version: 2.0.0
servers:
  - url: https://catalog-dev.phongvu.vn
    description: Develop server for dev and test
tags:
  - name: brand
    description: Brand management
  - name: product
    description: Product management
  - name: import
    description: Import operations
  - name: sale_channels
    description: Sale channel
  - name: product_line
    description: Product line
  - name: upload
    description: Upload operations
  - name: sale_category
    description: Slae category operations
  - name: extra

components:
  securitySchemes:
    IAMAuth:
      $ref: components/securitySchemes/IAMAuth.yml

security:
  - IAMAuth: []

paths:
  /brands:
    get:
      tags:
        - brand
      summary: Get list of brand
      parameters:
        $ref: components/parameters/@brands.yml#/get
      responses:
        $ref: components/responses/@brands.yml#/get
    post:
      tags:
        - brand
      summary: Create new brand
      requestBody:
        $ref: components/requestBodies/@brands.yml#/post
      responses:
        $ref: components/responses/@brands.yml#/post
  /brands/{brand_id}:
    patch:
      tags:
        - brand
      summary: Patch brand
      parameters:
        $ref: components/parameters/@brands@{brandId}.yml#/patch
      requestBody:
        $ref: components/requestBodies/@brands@{brandId}.yml#/patch
      responses:
        $ref: components/responses/@brands@{brandId}.yml#/patch
    get:
      tags:
        - brand
      summary: Get detail brand
      parameters:
        $ref: components/parameters/@brands@{brandId}.yml#/get
      responses:
        $ref: components/responses/@brands@{brandId}.yml#/get
  /extra-data:
    get:
      tags:
        - extra
      parameters:
        $ref: components/parameters/@extra-data.yml#/get
      responses:
        $ref: components/responses/@extra-data.yml#/get
  /import/history:
    get:
      tags:
        - import
      summary: Get import history
      parameters:
        $ref: components/parameters/@import@history.yml#/get
      responses:
        $ref: components/responses/@import@history.yml#/get
  /upload/doc:
    post:
      summary: Upload excel file for import product
      tags:
        - upload
      requestBody:
        $ref: components/requestBodies/@upload@doc.yml#/post
      responses:
        $ref: components/responses/@upload@doc.yml#/post
  /upload/image:
    post:
      summary: Upload logo product image
      tags:
        - upload
      requestBody:
        $ref: components/requestBodies/@upload@image.yml#/post
      responses:
        $ref: components/responses/@upload@image.yml#/post
  /product_lines:
    get:
      summary: Get product line
      tags:
        - product_line
      responses:
        $ref: components/responses/@product_lines.yml#/get
  '/product_lines/{line_id}/category':
    get:
      summary: List of category for product line
      tags:
        - product_line
      parameters:
        $ref: components/parameters/@product_lines@{line_id}@category.yml#/get
      responses:
        $ref: components/responses/@product_lines@{line_id}@category.yml#/get
  /sale_categories:
    post:
      summary: Create new sale category
      tags:
        - sale_category
      requestBody:
        $ref: components/requestBodies/@sale_categories.yml#/post
      responses:
        $ref: components/responses/@sale_categories.yml#/post
    get:
      tags:
        - sale_category
      parameters:
        $ref: components/parameters/@sale_categories.yml#/get
  '/sale_categories/{id_node}/position':
    patch:
      summary: Move sale category node in sale category tree
      tags:
        - sale_category
      parameters:
        $ref: components/parameters/@sale_categories@{id_node}@position.yml#/patch
      requestBody:
        $ref: components/requestBodies/@sale_categories@{id_node}@position.yml#/patch
      responses:
        $ref: components/responses/@sale_categories@{id_node}@position.yml#/patch
  '/sale_categories/{sale_category_id}/children':
    get:
      summary: Get sale category tree with sale category as root
      tags:
        - sale_category
      parameters:
        $ref: components/parameters/@sale_categories@{sale_category_id}@children.yml#/get
      responses:
        $ref: components/responses/@sale_categories@{sale_category_id}@children.yml#/get
  /sale_categories/{sale_category_id}:
    patch:
      summary: Patch sale category
      tags:
        - sale_category
      parameters:
        $ref: components/parameters/@sale_categories@{sale_category_id}.yml#/patch
      requestBody:
        $ref: components/requestBodies/@sale_categories@{sale_category_id}.yml#/patch
      responses:
        $ref: components/responses/@sale_categories@{sale_category_id}.yml#/patch
  /sale_channels:
    get:
      summary: Get sale channel list
      tags:
        - sale_channels
      parameters:
        $ref: components/parameters/@sale_channels.yml#/get
      responses:
        $ref: components/responses/@sale_channels.yml#/get
    post:
      summary: Create new sale channel
      tags:
        - sale_channels
      requestBody:
        $ref: components/requestBodies/@sale_channels.yml#/post
      responses:
        $ref: components/responses/@sale_channels.yml#/post
  '/sale_channels/{sale_channel_id}':
    patch:
      summary: Patch sale channel
      tags:
        - sale_channels
      parameters:
        $ref: components/parameters/@sale_channels@{sale_channel_id}.yml#/patch
      requestBody:
        $ref: components/requestBodies/@sale_channels@{sale_channel_id}.yml#/patch
      responses:
        $ref: components/responses/@sale_channels@{sale_channel_id}.yml#/patch
    get:
      summary: Get sale channel detail
      tags:
        - sale_channels
      parameters:
        $ref: components/parameters/@sale_channels@{sale_channel_id}.yml#/get
      responses:
        $ref: components/responses/@sale_channels@{sale_channel_id}.yml#/get
